sudo: false
language: erlang
notifications:
  email: false
otp_release:
  - 22.3

before_deploy:
  - rebar3 as prod tar

deploy:
  provider: releases
  api_key:
    secure: ZTuFyc1MhlO2O7izikE0YErG1WREC4ZTudnYAkJGVqyLl3YhJ7HjBzUCW+CLUfdQU6MHc1je4r9NV0fuPFQaRMCwsH5WvkW/H7YXvOBjs887EnzUq/sRWc3CgG4R/qzaJK/QQoue1rvFZHoVBQcfdpn4HC6Zs3HRgPZl/H6W57CYR/IhjSvrkLjOexyHuXyfIMC9tvBf6xZN6qvnYs2vetR6ZlNbPp2FGyWzSKHkxtRnugjm31GhhDWFcWrJwyer1DK1zM+wwpQjKXdercwnFW+0LTclTwkBXLXMpEexC5Pca4ym/1q5hmbwZN0g9hQDtc8blleAPnNjp/rpA+TToOTpzocLINVKCXttPyvBtZPmWE5gOQIpE7Qgx0hYFOx/ExLjJal8teIs1SPyYJjQa5c5T0vN9PPyXOofqz1tDeYauqWL+RUHDsZhE9Ddb9RMjlBCBJ/MxDPD7quKxYwWmIByI0q873JsS+C3de+R3nwnMkV5T75608wCJFmwTIxymlOOChPI91Rt9mHSsQhB/OYdchEc8JxJj/7v891Z7iqSquLOL1eMLPWYu/40qbEfO3pGkmZ/xfGOm2i/SslPOk6hy2bhwVIH6RjHhGcNo1AaDh0GGxkd/+/zCUB45xfZJ7n2ogQLETMmopKmrAufqixVXQudmGwKNtm9Si5WyGM=
  skip_cleanup: true
  file_blob: true
  file:
    - _build/prod/rel/smartlb/*.tar.gz
  on:
    tags: true
    repo: appcrash/smartlb
