name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Package
      uses: appcrash/centos-erlang@main
      with:
        rebar3_arg: as prod tar

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: smartlb
        path: _build/prod/rel/smartlb/*.tar.gz
    
