name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [7,8]
    container: appcrash/centos-erlang:${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - name: Package
      run: rebar3 as prod tar

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: smartlb-centos${{ matrix.os }} 
        path: _build/prod/rel/smartlb/*.tar.gz
    
